### ISSUE TITLE
Display mongoose file within index.ejs

### ISSUE THREAD

**Issue by jess-alexander** [jess-alexander/RESTfulPractice1#7]
ReferenceError: /Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/views/index.ejs:5
   3| <h1>All My Shoes </h1>
   4| 
**>> 5| <%= shoes %>**
   6| 
   7| </div>
   8| <% include ./partials/footer %>

**shoes is not defined**
   at eval (eval at <anonymous> (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/ejs/lib/ejs.js:495:12), <anonymous>:22:23)
   at returnedFn (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/ejs/lib/ejs.js:524:17)
   at View.exports.renderFile [as engine](/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/ejs/lib/ejs.js:378:31)
   at View.render (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/view.js:126:8)
   at tryRender (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/application.js:639:10)
   at EventEmitter.render (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/application.js:591:3)
   at ServerResponse.render (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/response.js:960:7)
   at /Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/index.js:61:6
   at Layer.handle [as handle_request](/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request](/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/router/layer.js:95:5)
   at /Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/express/lib/router/index.js:271:10)
   at methodOverride (/Users/Jess/webdevbootcamp/RESTfulRouting/RESTfulPractice1/node_modules/method-override/index.js:65:14)

**Comment by jess-alexander** [comment]
Corrected Issue. Clarified variable naming and specified which "shoe" was to be displayed.
